# Generated by Django 3.0.4 on 2020-03-13 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funder',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researchcategory',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AlterField(
            model_name='researcharea',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2mexample.ResearchCategory'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='owner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='m2mexample.Person'),
        ),
    ]
