# Generated by Django 3.0.4 on 2020-03-13 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0002_auto_20200313_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='HEResearchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('related_to', models.ManyToManyField(blank=True, to='m2mexample.Relationship')),
            ],
        ),
        migrations.CreateModel(
            name='HEResearchArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, null=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2mexample.ResearchCategory')),
                ('related_to', models.ManyToManyField(blank=True, to='m2mexample.Relationship')),
            ],
        ),
    ]
