# Generated by Django 3.0.4 on 2020-03-13 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0003_heresearcharea_heresearchcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heresearcharea',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2mexample.HEResearchCategory'),
        ),
    ]
