# Generated by Django 3.0.4 on 2020-03-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0004_auto_20200313_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heresearcharea',
            name='category',
        ),
        migrations.AddField(
            model_name='heresearcharea',
            name='hecategory',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='m2mexample.HEResearchCategory'),
        ),
    ]
