# Generated by Django 3.0.4 on 2020-03-15 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0007_heresearchcategory_strapline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funder',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='heresearcharea',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='heresearchcategory',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='person',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='researcharea',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='researchcategory',
            name='related_to',
        ),
        migrations.RemoveField(
            model_name='researchproject',
            name='related_to',
        ),
    ]
