# Generated by Django 3.0.4 on 2020-03-15 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('m2mexample', '0008_auto_20200315_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='relationship',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
