# Generated by Django 3.0.4 on 2020-03-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m2mexample', '0009_auto_20200315_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='object_id',
        ),
        migrations.AddField(
            model_name='funder',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='heresearcharea',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='heresearchcategory',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='person',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researcharea',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researchcategory',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
        migrations.AddField(
            model_name='researchproject',
            name='related_to',
            field=models.ManyToManyField(blank=True, to='m2mexample.Relationship'),
        ),
    ]
